insert into answers (id, text, correct, question_id) values (1, 'Время Тахрира', false, 1);
insert into answers (id, text, correct, question_id) values (2, 'Арабская весна', true, 1);
insert into answers (id, text, correct, question_id) values (3, 'Середина осени', false, 1);
insert into answers (id, text, correct, question_id) values (4, 'Мусульманский год', false, 1);
insert into answers (id, text, correct, question_id) values (5, 'Бозон Халли', false, 2);
insert into answers (id, text, correct, question_id) values (6, 'Бозон Хаддока', false, 2);
insert into answers (id, text, correct, question_id) values (7, 'Бозон озона', false, 2);
insert into answers (id, text, correct, question_id) values (8, 'Бозон Хиггса', true, 2);
insert into answers (id, text, correct, question_id) values (9, 'Ниневия', false, 3);
insert into answers (id, text, correct, question_id) values (10, 'Урук', false, 3);
insert into answers (id, text, correct, question_id) values (11, 'Вавилон', false, 3);
insert into answers (id, text, correct, question_id) values (12, 'Пальмира', true, 3);
insert into answers (id, text, correct, question_id) values (13, 'Япония', false, 4);
insert into answers (id, text, correct, question_id) values (14, 'Германия', false, 4);
insert into answers (id, text, correct, question_id) values (15, 'США', false, 4);
insert into answers (id, text, correct, question_id) values (16, 'Китай', true, 4);
insert into answers (id, text, correct, question_id) values (17, 'Франция', false, 5);
insert into answers (id, text, correct, question_id) values (18, 'США', true, 5);
insert into answers (id, text, correct, question_id) values (19, 'Россия', false, 5);
insert into answers (id, text, correct, question_id) values (20, 'Англия', false, 5);
insert into answers (id, text, correct, question_id) values (21, 'В. В. Жириновский', false, 6);
insert into answers (id, text, correct, question_id) values (22, 'Б. Н. Ельцин', false, 6);
insert into answers (id, text, correct, question_id) values (23, 'Д. А. Медведев', false, 6);
insert into answers (id, text, correct, question_id) values (24, 'В. В. Путин', true, 6);
insert into answers (id, text, correct, question_id) values (25, 'Башня Джидды', true, 7);
insert into answers (id, text, correct, question_id) values (26, 'Бурдж-Халифа', false, 7);
insert into answers (id, text, correct, question_id) values (27, 'Башня Падишаха', false, 7);
insert into answers (id, text, correct, question_id) values (28, 'Лахта-центр', false, 7);
insert into answers (id, text, correct, question_id) values (29, 'Ответный удар', false, 8);
insert into answers (id, text, correct, question_id) values (30, 'Копье Нептуна', true, 8);
insert into answers (id, text, correct, question_id) values (31, 'Шок и трепет', false, 8);
insert into answers (id, text, correct, question_id) values (32, 'Меч правосудия', false, 8);
insert into answers (id, text, correct, question_id) values (33, 'Переход на "зимнее время"', true, 9);
insert into answers (id, text, correct, question_id) values (34, 'Орден Андрея Первозванного', false, 9);
insert into answers (id, text, correct, question_id) values (35, 'Старый закон о соотечественниках', false, 9);
insert into answers (id, text, correct, question_id) values (36, 'Пост в твиттере', false, 9);
insert into answers (id, text, correct, question_id) values (37, 'Twitter', false, 10);
insert into answers (id, text, correct, question_id) values (38, 'Facebook', false, 10);
insert into answers (id, text, correct, question_id) values (39, 'LinkeIn', true, 10);
insert into answers (id, text, correct, question_id) values (40, 'ВКонтакте', false, 10);
insert into answers (id, text, correct, question_id) values (41, '2005', true, 11);
insert into answers (id, text, correct, question_id) values (42, '2003', false, 11);
insert into answers (id, text, correct, question_id) values (43, '2009', false, 11);
insert into answers (id, text, correct, question_id) values (44, '1997', false, 11);
insert into answers (id, text, correct, question_id) values (45, 'Билл Гейтс', false, 12);
insert into answers (id, text, correct, question_id) values (46, 'Павел Дуров', false, 12);
insert into answers (id, text, correct, question_id) values (47, 'Джек Дорси', false, 12);
insert into answers (id, text, correct, question_id) values (48, 'Марк Цукерберг', true, 12);
insert into answers (id, text, correct, question_id) values (49, '2007', false, 13);
insert into answers (id, text, correct, question_id) values (50, '2010', false, 13);
insert into answers (id, text, correct, question_id) values (51, '2005', true, 13);
insert into answers (id, text, correct, question_id) values (52, '2000', false, 13);
insert into answers (id, text, correct, question_id) values (53, 'MacHack', false, 14);
insert into answers (id, text, correct, question_id) values (54, 'youMac', false, 14);
insert into answers (id, text, correct, question_id) values (55, 'MacMan', true, 14);
insert into answers (id, text, correct, question_id) values (56, 'Intel', false, 14);
