insert into questions (id, text, theme_id) values (1, 'Как называется революционные движения, которые произошли в арабском мире в 2011 году?', 1);
insert into questions (id, text, theme_id) values (2, 'В июле 2012 года была обнаружена важная элементарная. Как она называется?', 1);
insert into questions (id, text, theme_id) values (3, 'Памятники какого древнего города разрушили повстанцы ИГИЛ весной 2015 года?', 1);
insert into questions (id, text, theme_id) values (4, 'В какой стране было произведено наибольшое количество автомобильных средств в 2015 году?', 1);
insert into questions (id, text, theme_id) values (5, 'В какой стране был основан ebay?', 1);
insert into questions (id, text, theme_id) values (6, 'Кто официально вступил в должность президента России 7 мая 2000 года?', 1);
insert into questions (id, text, theme_id) values (7, 'Небоскреб, который строится в Саудовской Аравии и который будет первым зданием на планете, чья высота близка к километру?', 1);
insert into questions (id, text, theme_id) values (8, 'Какое кодовое название носила операция по уничтожению Бен Ладена в мае 2011 года?', 1);
insert into questions (id, text, theme_id) values (9, 'Что отменил Дмитрий Медведев 8 февраля 2011 года?', 1);
insert into questions (id, text, theme_id) values (10, 'Какая соцсеть отказалась хранить персональные данные в России в марте 2017 года?', 1);
insert into questions (id, text, theme_id) values (11, 'Ураган Катрина вызывает хаос в США, а Ebay покупает Skype за 1,7 миллиардов евро. В каком году?', 1);
insert into questions (id, text, theme_id) values (12, 'Аккаунты какого из этих знаменитых айтишников были взломаны, так как имели "слабый" пароль?', 1);
insert into questions (id, text, theme_id) values (13, 'В каком году запустили видео-сайт Youtube?', 1);
insert into questions (id, text, theme_id) values (14, 'Как Стив Джобс назвал стационарный компьютер iMac, прежде чем он получил название iMac?', 1);