"""game.completed set default = false

Revision ID: fb9bb796e461
Revises: 93e11b443217
Create Date: 2021-09-22 13:14:53.729779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb9bb796e461'
down_revision = '93e11b443217'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players_scores', 'points',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players_scores', 'points',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
